name = "llm-cache-worker"
type = "typescript"

account_id = "7b107f3b348adbaf296afbff9802037a"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2023-12-07"

kv_namespaces = [
  { binding = "carebot_cache", id = "f74b667a82914244893d7dca35564777" }
]

