name: Typecheck

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

        # install types node
      - name: Install types node
        run: npm install --save-dev @types/node

      - name: Run typecheck
        run: npm run typecheck
