name: Typecheck

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies in client
        run: cd client && npm ci

      - name: Run typecheck in client
        run: cd client && npx tsc --noEmit

      - name: Install dependencies in server
        run: cd server && npm ci

      - name: Run typecheck in server
        run: cd server && npx tsc --noEmit
