name: Typecheck

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install root dependencies
        run: npm install

      - name: Install client dependencies
        run: cd client && npm install

      - name: Install worker dependencies
        run: cd worker && npm install

      - name: Install server dependencies
        run: cd server && npm install

      - name: Run typecheck
        run: npm run typecheck
